name: daily-post
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
jobs:
  post-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: run
        env:
          TISTORY_ACCESS_TOKEN: ${{ secrets.TISTORY_ACCESS_TOKEN }}
        run: python main.py
